# Generated by Django 5.2.7 on 2025-11-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='appointments/designs/'),
        ),
    ]
